name: grip
description: Grip For Ladies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  introduction_screen: ^3.1.11
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  toast: ^0.3.0
  json_serializable: ^6.7.1
  top_snackbar_flutter: ^3.1.0
  progress_dialog_null_safe: ^1.0.7
  connectivity_plus: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:

  flutter_lints: ^2.0.2

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/





