// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqt_KtVlme4fZgvF-t88DQvoKFk1fhltQ',
    appId: '1:854617148065:web:f778331eed5ed639c5bee0',
    messagingSenderId: '854617148065',
    projectId: 'grip-notification',
    authDomain: 'grip-notification.firebaseapp.com',
    storageBucket: 'grip-notification.appspot.com',
    measurementId: 'G-XS8HVM0YDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACjDvOOC2zRV7u1bbvQ9PnSZ3XZMPgZRU',
    appId: '1:854617148065:android:5c942a5d25fc91d3c5bee0',
    messagingSenderId: '854617148065',
    projectId: 'grip-notification',
    storageBucket: 'grip-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaX_kE9YqomGBu5fWr5qMGu2IW-pUFG2E',
    appId: '1:854617148065:ios:a4cb555d926d036dc5bee0',
    messagingSenderId: '854617148065',
    projectId: 'grip-notification',
    storageBucket: 'grip-notification.appspot.com',
    iosClientId: '854617148065-r429r2nttogd63u13q04687fs07fd84e.apps.googleusercontent.com',
    iosBundleId: 'com.jd.gripladies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaX_kE9YqomGBu5fWr5qMGu2IW-pUFG2E',
    appId: '1:854617148065:ios:a404650dc490fd89c5bee0',
    messagingSenderId: '854617148065',
    projectId: 'grip-notification',
    storageBucket: 'grip-notification.appspot.com',
    iosClientId: '854617148065-di90011lk4i0ucjmaaqinjiso3mb5853.apps.googleusercontent.com',
    iosBundleId: 'com.example.grip.RunnerTests',
  );
}
